import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RainbowProviders } from "./providers";
import { ThemeProvider } from "@/components/theme-provider";
import { AccountAbstractionProvider } from "@/hooks/AccountAbstractionContext";
import Header from "../components/Header";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AccountAbstractionProvider>
          <RainbowProviders>
            <ThemeProvider attribute="class" defaultTheme="system">
              <Header />
              {children}
            </ThemeProvider>
          </RainbowProviders>
        </AccountAbstractionProvider>
      </body>
    </html>
  );
}
